# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Vortexio.Vortexio
PackageVersion: 0.3.71
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://updates.vortexio.cc/desktop/Vortexio.Setup.0.3.71.exe
  InstallerSha256: 4640E53B7FC09457A6E08B43F140AC2C4B1EB231B071AA0108D4DFC4555D62F4
ManifestType: installer
ManifestVersion: 1.12.0
